### ISSUE TITLE
Create additional functionality for Array Libraries

### ISSUE THREAD

**Issue by joshuahannan** [Majoolr/ethereum-libraries#14]
Right now we have functions implemented in the Array Libraries that we are using for our other libraries, but other types of functions could be useful in the future for different types of libraries and applications.  Some other functionality can be added based on what is found in other language's standard libraries, like underscore for Javascript.   Make sure you add test cases for all the new functionality

Keep in mind that returning dynamic arrays from externally called functions in Solidity will not be implemented until Metropolis, but how awesome would it be if we had functions ready for that when it comes out?

Josh can help with details of the Array Library

**Comment by diaswrd** [comment]
I'm on it. Will come up with a list of potential function candidates soon.
