### ISSUE TITLE
Doc clarification needed

### ISSUE THREAD

**Issue by ekkis** [Majoolr/ethereum-libraries#15]
in the README, under the section "Testing the library in truffle" the document states:

> 1. `git clone --recursive` or download the truffle directory. Each folder in the truffle directory correlates to the folders in your truffle installation.

huh? running `git clone --recursive` in my project directory just displays syntax.  should that be: `git clone --recursive https://github.com/Majoolr/ethereum-libraries`?

but then it instructs "or download the truffle directory" -- from where?

**Comment by Hackdom** [comment]
Great catch, the clone --recursive isn't going to work with this setup. We need to recommend subversion to grab just the truffle folder. I'll get it changed.

**Comment by Hackdom** [comment]
I updated the README files. I'm going to close this for now and let me know if there are any issues still.
