### ISSUE TITLE
BasicMathLib Events

### ISSUE THREAD

**Issue by eolszewski** [Majoolr/ethereum-libraries#35]
In [BasicMathLib.sol](https://github.com/Majoolr/ethereum-libraries/blob/master/BasicMathLib/BasicMathLib.sol), each function is declared as `constant` but can possibly emit an event. Wouldn't emitting an event modify state - making this not a constant function?

Just wondering :)

**Comment by Hackdom** [comment]
That's a good catch, I believe you are correct on that, the scope of state changes only considered the context of storage and not event logs. Considering the EVM hasn't enforced constant functions then it would be allowed to do so improperly. I'm wondering why the compiler allows it though and if that should be addressed.
