### ISSUE TITLE
TokenLib possibly re-initialisable for mintable tokens with zero initial supply

### ISSUE THREAD

**Issue by veox** [Majoolr/ethereum-libraries#41]
On [this line](https://github.com/Majoolr/ethereum-libraries/blob/97f3aac4584a73f353612fb303f147e290faaccd/TokenLib/TokenLib.sol#L71), a check is made that:

``` solidity
require(self.INITIAL_SUPPLY == 0);
```

It is my understanding that the above check is made as a substitute for a "storage has not been initialised" check. An implicit assumption is made that the token creator won't have an initial supply of 0.

I'm evaluating Majoolr for use in a mintable token where, by design, the initial supply is 0. For such a token, `init()` is under-protected.

-----

If my guess above is correct, I'd propose using a separate bool flag for that, the intent of which is   not collated with any other parameter. Something like:

``` solidity
require(self.initialised == false);
...
self.initialised = true;
```

-----

Tangent: although the [Solidity style guide](https://solidity.readthedocs.io/en/develop/style-guide.html#constants) suggests using all-caps for constants, it is IMO best reserved for _compile-time constants_. There is no storage write protection in the EVM (yet, TTBOMK), so the "constant" _may_ be overwritten in storage due to, say, a compiler bug (even if unlikely).

**Comment by Hackdom** [comment]
Yes, 100% on this, we’ll update on the next deploy and great eye on the workflow. We’ll discuss the styling and see what some of our folks think.
