### ISSUE TITLE
BasicMathLib emits events in constant functions

### ISSUE THREAD

**Issue by veox** [Majoolr/ethereum-libraries#46]
## What is it?

[Events are recorded as part of the transaction receipt](https://ethereum.stackexchange.com/questions/16117/proving-the-existence-of-logs-to-the-blockchain), so emitting events goes somewhat against the notion of "constantness".

### Problem

When using `TokenLib` (which itself uses `BasicMathLib`) in [a contract](https://gitlab.com/veox/oobiqoo/blob/master/contracts/oobiqoo.sol) that needs some experimental v0.5.0 features of Solidity - where `constant`/`view`/`pure` will be checked and/or enforced - a warning is emitted, highlighting the above discrepancy.

This warning may well turn into an error when Solidity v0.5 is released proper. It would be nice to have discussion now as to whether Majoolr's approach needs adjustment.

### Proposed solution

Do not emit events from within these functions. This should be up to those using the library - after all, an `err` indicator is also returned.

### Steps to reproduce

1. include BasicMathLib 1.1.0 in a contract;
2. specify `pragma experimental "v0.5.0" for said contract;
3. use `solc` >= v0.4.18 to compile it;
4. observe warnings:

```
oobiqoo.sol:5:1: Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental "v0.5.0";
^---------------------------^
oobiqoo.sol:37:5: Warning: No visibility specified. Defaulting to "public".
    function oobiqoo(address __owner) {
    ^
Spanning multiple lines.
majoolr/BasicMathLib.sol:49:7: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
      Err("times func overflow");
      ^------------------------^
majoolr/BasicMathLib.sol:67:5: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
    Err("tried to divide by zero");
    ^----------------------------^
majoolr/BasicMathLib.sol:87:7: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
      Err("plus func overflow");
      ^-----------------------^
majoolr/BasicMathLib.sol:106:7: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
      Err("minus func underflow");
      ^-------------------------^
```

**Comment by Hackdom** [comment]
Excellent catch @veox ! We actually just updated that, if you look in the BasicMathLib, we updated it to latest v0.4.18, used view, and removed events. This was part of the delay on getting to the TokenLib itself, the lower level libs needed updating. In the process of overhauling and getting to the TokenLib today. I'll ping you when that's finished.

**Comment by veox** [comment]
Ha!

If I had been more thorough, and had gone to fish for the link to BasicMathLib 1.1.0, I _would_ have seen this.

**Comment by Hackdom** [comment]
No worries, the whole repo needed some tender care :D

**Comment by veox** [comment]
Since it's [already done](https://github.com/Majoolr/ethereum-libraries/blob/3b609e99fee1aded5ecd6a23961e51c9e5e6bb2a/BasicMathLib/BasicMathLib.sol), I'll close the issue.

My current use of Majoolr is sloppy "import locally", so I'll just pull the changes in to squelch these warnings, and do the same for `TokenLib` when that's done, too.
